spring:
datasource:

driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://localhost:3306/user_and_emails?useTimezone=true&serverTimezone=UTC
username: root
password:
jpa:

ddl-auto: update
generate-ddl: true
properties:
hibernate:
dialect: org.hibernate.dialect.MySQLDialect
show-sql: true